const { Client } = require('pg');

async function initializeDatabase() {
    const client = new Client({
        host: 'localhost',
        user: 'postgres', // Change to your PostgreSQL username
        password: 'Sagar@1231', // Change to your PostgreSQL password
    });

    try {
        await client.connect();

        // Drop the database if it exists (for development purposes)
        await client.query(`DROP DATABASE IF EXISTS comparedoo`);
        console.log('Database comparedoo dropped (if existed)');

        // Create the database
        await client.query(`CREATE DATABASE comparedoo`);
        console.log('Database comparedoo created');

        // Disconnect and reconnect to the new database
        await client.end();

        const dbClient = new Client({
            host: 'localhost',
            user: 'postgres',
            password: 'Sagar@1231',
            database: 'comparedoo'
        });

        await dbClient.connect();

        // Create the table country_general_info
        await dbClient.query(`
            CREATE TABLE IF NOT EXISTS country_general_info (
            id SERIAL PRIMARY KEY,  -- SERIAL is the equivalent of AUTO_INCREMENT in PostgreSQL
            country VARCHAR(255) NOT NULL,
            capitalCity VARCHAR(255),
            largestCity VARCHAR(255),
            populationGrowthAnnual NUMERIC(22, 20),  -- DECIMAL in PostgreSQL is NUMERIC
            officialName VARCHAR(255),
            continent VARCHAR(100),
            landlockedStatus VARCHAR(100),
            nationalAnthemEnglish TEXT,
            nationalAnthemNative TEXT,
            currencyName VARCHAR(255),
            currencySymbol VARCHAR(20),
            nationalBird VARCHAR(100),
            nationalColors VARCHAR(255),
            nationalFlower VARCHAR(100),
            nationalSport VARCHAR(100),
            nationalAnimal VARCHAR(100),
            demonyms VARCHAR(255),
            drivingSide VARCHAR(20),
            callingCode VARCHAR(50),
            ISO3166Code VARCHAR(20),
            internetTLD VARCHAR(20),
            latitude VARCHAR(20),
            longitude VARCHAR(20),
            areaInSqKm DOUBLE PRECISION,  -- DOUBLE in PostgreSQL is DOUBLE PRECISION
            areaInSqMile DOUBLE PRECISION,
            waterPercentage VARCHAR(50),  -- Keeping VARCHAR since it’s more flexible for formatted strings
            officialLanguages TEXT,
            majorReligion VARCHAR(100),
            majorReligionPercentage REAL,  -- FLOAT can be converted to REAL for low precision floating-point numbers
            governmentStatus VARCHAR(100),
            totalTimezones TEXT,
            timezoneNormal TEXT,
            timezoneSummer TEXT,
            DST VARCHAR(50),
            DSTStart VARCHAR(50),
            DSTEnd VARCHAR(50),
            DSTDuration VARCHAR(50),
            population TEXT,
            age0_14 REAL,  -- REAL is a lower precision floating-point number
            age15_64 REAL,
            age65Plus REAL,
            fertilityRate DOUBLE PRECISION,
            mortalityRateFemale DOUBLE PRECISION,
            mortalityRateMale DOUBLE PRECISION,
            infantMortalityRate DOUBLE PRECISION,
            topCauseOfDeath VARCHAR(255),
            topCauseOfDeathNumber REAL,
            lowestCauseOfDeath VARCHAR(255),
            lowestCauseOfDeathNumber REAL,
            roadTrafficDeaths REAL,
            suicideDeaths REAL,
            numberOfNewHIVInfections REAL,
            prevalenceOfHypertensionPercentage REAL,
            adultObesityPercentage REAL,
            tobaccoConsumptionPercentage REAL,
            alcoholConsumptionPercentage REAL,
            startOfWeek VARCHAR(20),
            unitValueInUSD REAL
            );
        `);

        // Create the table country_cost_info
        await dbClient.query(`
            CREATE TABLE IF NOT EXISTS country_cost_info (
            id SERIAL PRIMARY KEY,
            country VARCHAR(255) NOT NULL,
            rent1bedroomflatInCityCenter REAL,
            rent2bedroomflatInCityCenter REAL,
            rent3bedroomflatInCityCenter REAL,
            rent1bedroomflatOutsideCityCenter REAL,
            rent2bedroomflatOutsideCityCenter REAL,
            rent3bedroomflatOutsideCityCenter REAL,
            mortgageRatesPerMonth REAL,
            realEstateAgentsCommissionFees REAL,
            homeFurnishing REAL,
            electricityCostPerMonth REAL,
            heatingCostPerMonth REAL,
            coolingCostPerMonth REAL,
            waterCostPerMonth REAL,
            wifiCostPerMonth REAL,
            mobilePhonePlanCostPerMonth REAL,
            cableTVServicePerMonth REAL,
            landlinePhoneServicePerMonth REAL,
            milk1Liter REAL,
            water1Liter REAL,
            bread500g REAL,
            rice1Kg REAL,
            eggsDozen REAL,
            cheese1Kg REAL,
            chickenBreasts1Kg REAL,
            beef1Kg REAL,
            apples1Kg REAL,
            bananas1Kg REAL,
            oranges1Kg REAL,
            tomatoes1Kg REAL,
            potatoes1Kg REAL,
            lemons1Kg REAL,
            onions1Kg REAL,
            lentils1Kg REAL,
            wineMidRangeBottle REAL,
            glassOfWine REAL,
            domesticBeerHalfLiter REAL,
            importedBeerHalfLiter REAL,
            domesticAlcohol1Liter REAL,
            brandedAlcohol1Liter REAL,
            mealAtInexpensiveRestaurant REAL,
            threeCourseMealForTwo REAL,
            fastFoodComboMeal REAL,
            coffee REAL,
            softDrink REAL,
            pizza REAL,
            takeoutDeliveryMeal REAL,
            cigarettesPackOf20 REAL,
            publicTransportPass REAL,
            singlePublicTransportTicket REAL,
            trainTickets REAL,
            airfareDomestic REAL,
            taxiStartFare REAL,
            taxiRatePerKm REAL,
            carRentalPerDay REAL,
            parkingFeesCityCenterPerHour REAL,
            parkingFeesOutsideCityCenterPerHour REAL,
            fuelPerLiter REAL,
            fuelPerGallon REAL,
            carInsurance REAL,
            carMaintenance REAL,
            vehicleRegistration REAL,
            tollFees REAL,
            carLoanInterestRates REAL,
            vehiclePurchasePrice REAL,
            drivingLicenseFees REAL,
            doctorsVisit REAL,
            specialistsVisit REAL,
            dentistsVisit REAL,
            eyeExam REAL,
            prescriptionMedication REAL,
            overTheCounterMedication REAL,
            healthInsurancePremiums REAL,
            healthInsuranceDeductibles REAL,
            emergencyRoomVisit REAL,
            hospitalStayPerNight REAL,
            physicalTherapy REAL,
            mentalHealthCounseling REAL,
            vaccinations REAL,
            preventiveHealthScreenings REAL,
            cosmeticProcedures REAL,
            opticalGlasses REAL,
            contactLenses REAL,
            shampooPrice REAL,
            toothpastePrice REAL,
            haircuts REAL,
            hairColoring REAL,
            manicurePedicureCost REAL,
            spaTreatment REAL,
            pairOfNikeRunningShoes REAL,
            mensDressShirt REAL,
            mensSuit REAL,
            mensJeans REAL,
            mensCasualShoes REAL,
            mensFormalShoes REAL,
            womensDress REAL,
            womensJeans REAL,
            womensCasualShoes REAL,
            womensFormalShoes REAL,
            winterCoatForAdults REAL,
            summerDress REAL,
            sweater REAL,
            underwearMen REAL,
            underwearWomen REAL,
            socksMen REAL,
            socksWomen REAL,
            sportsWear REAL,
            movieTicket REAL,
            theaterTicket REAL,
            concertTicket REAL,
            sportsEventTicket REAL,
            gymMembership REAL,
            swimmingPoolAccess REAL,
            museumEntry REAL,
            zooEntry REAL,
            amusementParkEntry REAL,
            bowling REAL,
            miniGolf REAL,
            videoGames REAL,
            streamingServices REAL,
            outdoorEquipmentRental REAL,
            themeParkAnnualPass REAL,
            childrensJeans REAL,
            childrensSneakers REAL,
            childrensWinterCoat REAL,
            daycareInfant REAL,
            daycareToddler REAL,
            childcareForSickDays REAL,
            earlyChildhoodEducationPrograms REAL,
            extracurricularActivities REAL,
            summerCamp REAL,
            preSchool REAL,
            primarySchoolFees REAL,
            secondarySchoolFees REAL,
            privateSchoolFees REAL,
            universityTuition REAL,
            universityTuitionPrivate REAL,
            afterSchoolActivities REAL,
            specialEducationServices REAL,
            tutoring REAL,
            textbooks REAL,
            schoolSupplies REAL,
            languageClasses REAL,
            parentingClasses REAL,
            fitnessClass REAL,
            musicLessons REAL,
            danceLessons REAL,
            artClasses REAL,
            readingMaterials REAL,
            educationalSoftware REAL,
            averageGrossSalary REAL,
            averageNetSalary REAL,
            minimumWage REAL,
            socialSecurityContributions REAL,
            pensionContributions REAL,
            costOfLivingIndex REAL,
            medianHouseholdIncome REAL,
            averageBonus REAL,
            legalConsultationPerHourRate REAL,
            accountingServicesPerHourRate REAL,
            ITSupportServicesPerHourRate REAL,
            technicianServicesPerHourRate REAL
            );
        `);

        // Create the table country_standard_info
        await dbClient.query(`
            CREATE TABLE IF NOT EXISTS country_standard_info (
            id SERIAL PRIMARY KEY,
            country VARCHAR(255) NOT NULL,
            GDPNominal VARCHAR(50),
            GDPPerCapita REAL,
            GINI REAL,
            inflationOnConsumerPrices REAL,
            centralGovernmentDebt REAL,
            HDI NUMERIC(5, 3) NULL,
            humanCapitalIndex REAL,
            literacyRate REAL,
            lifeExpectancyRatio REAL,
            healthyLifeExpectancyRatio REAL,
            povertyRatio REAL,
            unemploymentPercentageOfTotalLabourForce REAL,
            grossNationalExpenditure REAL,
            currentHealthExpenditurePercentage REAL,
            researchAndDevelopmentExpenditure REAL,
            governmentExpenditureOnEducation REAL,
            internationalTourismExpenditureUSD REAL,
            numberOfInternationalTouristsArrival INT,
            militaryExpenditure REAL,
            densityOfDoctorsNumber REAL,
            densityOfNursesNumber REAL,
            densityOfPharmacistsNumber REAL,
            hospitalBedsPer1000Peoples REAL,
            pregnantWomenReceivingPrenatalCare REAL,
            agriculturalLand REAL,
            forestArea REAL,
            CO2Emission REAL,
            accessToElectricity REAL,
            accessToInternet REAL,
            annualFreshWaterWithdrawls REAL,
            timeRequiredToStartABusinessDays REAL,
            newBusinessesRegisteredNumber INT,
            newBusinessesRegistrationDensityPer1000People REAL,
            costOfBusinessStartUpProcedures REAL,
            importsOfGoodsAndServicesPercentageOfGDP REAL,
            fuelImportsPercentageOfMerchandiseImports REAL,
            costToImportBorderComplianceUSD REAL,
            costToImportDocumentryComplianceUSD REAL,
            timeToImportBorderComplianceHours REAL,
            timeToImportDocumentryComplianceHours REAL,
            exportsOfGoodsAndServicesPercentageOfGDP REAL,
            fuelExportsPercentageOfMerchandiseExports REAL,
            costToExportBorderComplianceUSD REAL,
            costToExportDocumentryComplianceUSD REAL,
            timeToExportBorderComplianceHours REAL,
            timeToExportDocumentryComplianceHours REAL,
            grossNationalSavings REAL,
            taxRevenue REAL,
            taxesOnExportsPercentageOfTaxRevenue REAL,
            taxesOnGoodsAndServicesPercentageOfRevenue REAL,
            taxesOnInternationalTradePercentageOfRevenue REAL,
            timeToPrepareAndPayTaxesHours REAL,
            customsAndOtherImportDutiesPercentageOfTaxRevenue REAL,
            corporateTaxRates VARCHAR(20),
            incomeTaxRates VARCHAR(20),
            salesTaxRates VARCHAR(20),
            propertyTaxRates VARCHAR(20),
            currencySymbol VARCHAR(20)
            );
        `);

        // Create the table us_state_general_info
        await dbClient.query(`
            CREATE TABLE IF NOT EXISTS us_state_general_info (
            id SERIAL PRIMARY KEY,
            state VARCHAR(255) NOT NULL,
            officialName VARCHAR(255),
            nicknames VARCHAR(255),
            landlockedStatus VARCHAR(20),
            capitalCity VARCHAR(255),
            latitude VARCHAR(50),
            longitude VARCHAR(50),
            mottoLatin VARCHAR(255),
            mottoEnglish VARCHAR(255),
            stateAnthemNative VARCHAR(255),
            stateAnthemEnglish VARCHAR(255),
            largestCity VARCHAR(255),
            demonyms VARCHAR(255),
            officialWebsites VARCHAR(50),
            ISO3166Code VARCHAR(20),
            areaInSqMile REAL,
            areaInSqKm REAL,
            waterPercentage VARCHAR(20),
            officialLanguages TEXT,
            stateAnimal VARCHAR(100),
            stateBird VARCHAR(100),
            stateFlower VARCHAR(100),
            stateColors VARCHAR(100),
            stateSport VARCHAR(100),
            stateTree VARCHAR(100),
            totalTimezones TEXT,
            timezoneNormal TEXT,
            timezoneSummer TEXT,
            DSTStart VARCHAR(50),
            DSTEnd VARCHAR(50),
            DSTDuration VARCHAR(20),
            population BIGINT,
            veteransPercentage REAL,
            veteransPercentageMale REAL,
            veteransPercentageFemale REAL,
            currencyName VARCHAR(50),
            currencySymbol VARCHAR(20),
            startOfWeek VARCHAR(20),
            drivingSide VARCHAR(20),
            callingCode VARCHAR(50)
            );
        `);

        // Create the table us_state_cost_info
        await dbClient.query(`
            CREATE TABLE IF NOT EXISTS us_state_cost_info (
            id SERIAL PRIMARY KEY,
            state VARCHAR(255) NOT NULL,
            rent1bedroomflatInCityCenter REAL,
            rent2bedroomflatInCityCenter REAL,
            rent3bedroomflatInCityCenter REAL,
            rent1bedroomflatOutsideCityCenter REAL,
            rent2bedroomflatOutsideCityCenter REAL,
            rent3bedroomflatOutsideCityCenter REAL,
            mortgageRatesPerMonth REAL,
            realEstateAgentsCommissionFees REAL,
            homeFurnishing REAL,
            electricityCostPerMonth REAL,
            heatingCostPerMonth REAL,
            coolingCostPerMonth REAL,
            waterCostPerMonth REAL,
            wifiCostPerMonth REAL,
            mobilePhonePlanCostPerMonth REAL,
            cableTVServicePerMonth REAL,
            landlinePhoneServicePerMonth REAL,
            milk1Liter REAL,
            water1Liter REAL,
            bread500g REAL,
            rice1Kg REAL,
            eggsDozen REAL,
            cheese1Kg REAL,
            chickenBreasts1Kg REAL,
            beef1Kg REAL,
            apples1Kg REAL,
            bananas1Kg REAL,
            oranges1Kg REAL,
            tomatoes1Kg REAL,
            potatoes1Kg REAL,
            lemons1Kg REAL,
            onions1Kg REAL,
            lentils1Kg REAL,
            wineMidRangeBottle REAL,
            glassOfWine REAL,
            domesticBeerHalfLiter REAL,
            importedBeerHalfLiter REAL,
            domesticAlcohol1Liter REAL,
            brandedAlcohol1Liter REAL,
            mealAtInexpensiveRestaurant REAL,
            threeCourseMealForTwo REAL,
            fastFoodComboMeal REAL,
            coffee REAL,
            softDrink REAL,
            pizza REAL,
            takeoutDeliveryMeal REAL,
            cigarettesPackOf20 REAL,
            publicTransportPass REAL,
            singlePublicTransportTicket REAL,
            trainTickets REAL,
            airfareDomestic REAL,
            taxiStartFare REAL,
            taxiRatePerKm REAL,
            carRentalPerDay REAL,
            parkingFeesCityCenterPerHour REAL,
            parkingFeesOutsideCityCenterPerHour REAL,
            fuelPerLiter REAL,
            fuelPerGallon REAL,
            carInsurance REAL,
            carMaintenance REAL,
            vehicleRegistration REAL,
            tollFees REAL,
            carLoanInterestRates REAL,
            vehiclePurchasePrice REAL,
            drivingLicenseFees REAL,
            doctorsVisit REAL,
            specialistsVisit REAL,
            dentistsVisit REAL,
            eyeExam REAL,
            prescriptionMedication REAL,
            overTheCounterMedication REAL,
            healthInsurancePremiums REAL,
            healthInsuranceDeductibles REAL,
            emergencyRoomVisit REAL,
            hospitalStayPerNight REAL,
            physicalTherapy REAL,
            mentalHealthCounseling REAL,
            vaccinations REAL,
            preventiveHealthScreenings REAL,
            cosmeticProcedures REAL,
            opticalGlasses REAL,
            contactLenses REAL,
            shampooPrice REAL,
            toothpastePrice REAL,
            haircuts REAL,
            hairColoring REAL,
            manicurePedicureCost REAL,
            spaTreatment REAL,
            pairOfNikeRunningShoes REAL,
            mensDressShirt REAL,
            mensSuit REAL,
            mensJeans REAL,
            mensCasualShoes REAL,
            mensFormalShoes REAL,
            womensDress REAL,
            womensJeans REAL,
            womensCasualShoes REAL,
            womensFormalShoes REAL,
            winterCoatForAdults REAL,
            summerDress REAL,
            sweater REAL,
            underwearMen REAL,
            underwearWomen REAL,
            socksMen REAL,
            socksWomen REAL,
            sportsWear REAL,
            movieTicket REAL,
            theaterTicket REAL,
            concertTicket REAL,
            sportsEventTicket REAL,
            gymMembership REAL,
            swimmingPoolAccess REAL,
            museumEntry REAL,
            zooEntry REAL,
            amusementParkEntry REAL,
            bowling REAL,
            miniGolf REAL,
            videoGames REAL,
            streamingServices REAL,
            outdoorEquipmentRental REAL,
            themeParkAnnualPass REAL,
            childrensJeans REAL,
            childrensSneakers REAL,
            childrensWinterCoat REAL,
            daycareInfant REAL,
            daycareToddler REAL,
            childcareForSickDays REAL,
            earlyChildhoodEducationPrograms REAL,
            extracurricularActivities REAL,
            summerCamp REAL,
            preSchool REAL,
            primarySchoolFees REAL,
            secondarySchoolFees REAL,
            privateSchoolFees REAL,
            universityTuition REAL,
            universityTuitionPrivate REAL,
            afterSchoolActivities REAL,
            specialEducationServices REAL,
            tutoring REAL,
            textbooks REAL,
            schoolSupplies REAL,
            languageClasses REAL,
            parentingClasses REAL,
            fitnessClass REAL,
            musicLessons REAL,
            danceLessons REAL,
            artClasses REAL,
            readingMaterials REAL,
            educationalSoftware REAL,
            averageGrossSalary REAL,
            averageNetSalary REAL,
            minimumWage REAL,
            socialSecurityContributions REAL,
            pensionContributions REAL,
            costOfLivingIndex REAL,
            medianHouseholdIncome REAL,
            averageBonus REAL,
            legalConsultationPerHourRate REAL,
            accountingServicesPerHourRate REAL,
            ITSupportServicesPerHourRate REAL,
            technicianServicesPerHourRate REAL
            );
        `);

        // Create the table us_state_standard_info
        await dbClient.query(`
            CREATE TABLE IF NOT EXISTS us_state_standard_info (
            id SERIAL PRIMARY KEY,
            state VARCHAR(255) NOT NULL,
            population INTEGER,
            HDI NUMERIC(5, 3),
            literacyRate REAL,
            lifeExpectancyRatio REAL,
            povertyRatio REAL,
            employmentRate REAL,
            GDPNominal REAL,
            GDPPerCapita REAL,
            GINI REAL,
            totalRegisteredPhysicians INTEGER,
            totalRegisteredNurses INTEGER,
            availableHospitalBeds INTEGER,
            disabilityPercentage REAL,
            populationWithoutHealthInsuranceCoverage REAL,
            salesTaxRates VARCHAR(50),
            propertyTaxRates VARCHAR(50),
            gasAndFuelTaxRatesPerGallon REAL,
            beerTaxPerGallon REAL,
            incomeTaxRates VARCHAR(50),
            corporateTaxRates VARCHAR(50),
            medianAge REAL,
            sexRatioMalesPer100Females REAL,
            age60to64 REAL,
            age65to74 REAL,
            age75to84 REAL,
            age85AndOver REAL,
            medianIncomeDollars REAL,
            agricultureForestryFishing REAL,
            construction REAL,
            manufacturing REAL,
            wholesaleTrade REAL,
            retailTrade REAL,
            transportationAndWarehousing REAL,
            ITAndInformation REAL,
            financeAndRealEstate REAL,
            educationAndHealthCare REAL,
            artsEntertainmentRecreation REAL,
            publicAdministration REAL,
            workFromHome REAL,
            meanTravelTimeToWorkMinutes REAL,
            privateWageandSalaryWorkers REAL,
            governmentWorkers REAL,
            selfEmployedInNotOwnIncorporatedBusiness REAL,
            accessToInternet REAL,
            accessToElectricity REAL,
            forestArea REAL,
            agriculturalLand REAL,
            highSchoolGraduate REAL,
            associateDegreePercentage REAL,
            bachelorsDegreePercentage REAL,
            graduateDegreePercentage REAL,
            onlyEnglishSpeakingPercentage REAL,
            whiteRace INTEGER,
            blackOrAfricanAmericanRace INTEGER,
            americanIndianAndAlaskaNativeRace INTEGER,
            asianRace INTEGER,
            hawaiianAndPacificIslanderRace INTEGER,
            twoOrMoreRaces INTEGER,
            hispanicOrLatino INTEGER,
            marriedCoupleHouseholdPercentage REAL,
            maleHouseholderPercentage REAL,
            femaleHouseholderPercentage REAL,
            averageFamilySize REAL,
            homeOwnershipRate REAL,
            medianGrossRent REAL,
            totalHousingUnits INTEGER,
            marriedNotSeparatedPopulationPercentageMale REAL,
            marriedNotSeparatedPopulationPercentageFemale REAL,
            neverMarriedPopulationPercentageMale REAL,
            neverMarriedPopulationPercentageFemale REAL,
            separatedPopulationPercentageMale REAL,
            separatedPopulationPercentageFemale REAL,
            divorcedPopulationPercentageMale REAL,
            divorcedPopulationPercentageFemale REAL,
            widowedPopulationPercentageMale REAL,
            widowedPopulationPercentageFemale REAL
        );
        `);

        console.log('Tables created successfully');
    } catch (error) {
        console.error('Failed to initialize the database:', error);
    } finally {
        await client.end();
    }
}

initializeDatabase();
