const mysql = require('mysql2/promise');

async function initializeDatabase() {
  const connection = await mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: 'Sagar@1231'
  });

  try {
    // Drop the database if it exists (for development purposes)
    await connection.query(`DROP DATABASE IF EXISTS comparedoo`);
    console.log('Database comparedoo dropped (if existed)');

    // Create the database 
    await connection.query(`CREATE DATABASE comparedoo`);
    console.log('Database comparedoo created');

    // Use the database
    await connection.query(`USE comparedoo`);

    // Create the table country_general_info
    await connection.query(`
            CREATE TABLE IF NOT EXISTS country_general_info (
              id INT AUTO_INCREMENT PRIMARY KEY,
              country VARCHAR(255) NOT NULL,
              capitalCity VARCHAR(255),
              largestCity VARCHAR(255),
              populationGrowthAnnual DECIMAL(22, 20) NULL, -- Decimal allows precision for growth rates
              officialName VARCHAR(255),
              continent VARCHAR(100),
              landlockedStatus VARCHAR(100),
              nationalAnthemEnglish TEXT,
              nationalAnthemNative TEXT,
              currencyName VARCHAR(255),
              currencySymbol VARCHAR(20),
              nationalBird VARCHAR(100),
              nationalColors VARCHAR(255),
              nationalFlower VARCHAR(100),
              nationalSport VARCHAR(100),
              nationalAnimal VARCHAR(100),
              demonyms VARCHAR(255),
              drivingSide VARCHAR(20),
              callingCode VARCHAR(50),
              ISO3166Code VARCHAR(20),
              internetTLD VARCHAR(20),
              latitude VARCHAR(20),
              longitude VARCHAR(20),
              areaInSqKm DOUBLE,
              areaInSqMile DOUBLE,
              waterPercentage VARCHAR(50), -- Assuming water percentage is a decimal value (0.00 - 100.00)
              officialLanguages TEXT,
              majorReligion VARCHAR(100),
              majorReligionPercentage FLOAT,
              governmentStatus VARCHAR(100),
              totalTimezones TEXT,
              timezoneNormal TEXT,
              timezoneSummer TEXT,
              DST VARCHAR(50),
              DSTStart VARCHAR(50),
              DSTEnd VARCHAR(50),
              DSTDuration VARCHAR(50),
              population TEXT,
              age0_14 FLOAT,
              age15_64 FLOAT,
              age65Plus FLOAT,
              fertilityRate DOUBLE,
              mortalityRateFemale DOUBLE,
              mortalityRateMale DOUBLE,
              infantMortalityRate DOUBLE,
              topCauseOfDeath VARCHAR(255),
              topCauseOfDeathNumber FLOAT,
              lowestCauseOfDeath VARCHAR(255),
              lowestCauseOfDeathNumber FLOAT,
              roadTrafficDeaths FLOAT,
              suicideDeaths FLOAT,
              numberOfNewHIVInfections FLOAT,
              prevalenceOfHypertensionPercentage FLOAT,
              adultObesityPercentage FLOAT,
              tobaccoConsumptionPercentage FLOAT,
              alcoholConsumptionPercentage FLOAT,
              startOfWeek VARCHAR(20),
              unitValueInUSD FLOAT
            );
          `);

    // Create the table country_cost_info
    await connection.query(`
            CREATE TABLE IF NOT EXISTS country_cost_info (
              id INT AUTO_INCREMENT PRIMARY KEY,
              country VARCHAR(255) NOT NULL,
              rent1bedroomflatInCityCenter FLOAT,
              rent2bedroomflatInCityCenter FLOAT,
              rent3bedroomflatInCityCenter FLOAT,
              rent1bedroomflatOutsideCityCenter FLOAT,
              rent2bedroomflatOutsideCityCenter FLOAT,
              rent3bedroomflatOutsideCityCenter FLOAT,
              mortgageRatesPerMonth FLOAT,
              realEstateAgentsCommissionFees FLOAT,
              homeFurnishing FLOAT,
              electricityCostPerMonth FLOAT,
              heatingCostPerMonth FLOAT,
              coolingCostPerMonth FLOAT,
              waterCostPerMonth FLOAT,
              wifiCostPerMonth FLOAT,
              mobilePhonePlanCostPerMonth FLOAT,
              cableTVServicePerMonth FLOAT,
              landlinePhoneServicePerMonth FLOAT,
              milk1Liter FLOAT,
              water1Liter FLOAT,
              bread500g FLOAT,
              rice1Kg FLOAT,
              eggsDozen FLOAT,
              cheese1Kg FLOAT,
              chickenBreasts1Kg FLOAT,
              beef1Kg FLOAT,
              apples1Kg FLOAT,
              bananas1Kg FLOAT,
              oranges1Kg FLOAT,
              tomatoes1Kg FLOAT,
              potatoes1Kg FLOAT,
              lemons1Kg FLOAT,
              onions1Kg FLOAT,
              lentils1Kg FLOAT,
              wineMidRangeBottle FLOAT,
              glassOfWine FLOAT,
              domesticBeerHalfLiter FLOAT,
              importedBeerHalfLiter FLOAT,
              domesticAlcohol1Liter FLOAT,
              brandedAlcohol1Liter FLOAT,
              mealAtInexpensiveRestaurant FLOAT,
              threeCourseMealForTwo FLOAT,
              fastFoodComboMeal FLOAT,
              coffee FLOAT,
              softDrink FLOAT,
              pizza FLOAT,
              takeoutDeliveryMeal FLOAT,
              cigarettesPackOf20 FLOAT,
              publicTransportPass FLOAT,
              singlePublicTransportTicket FLOAT,
              trainTickets FLOAT,
              airfareDomestic FLOAT,
              taxiStartFare FLOAT,
              taxiRatePerKm FLOAT,
              carRentalPerDay FLOAT,
              parkingFeesCityCenterPerHour FLOAT,
              parkingFeesOutsideCityCenterPerHour FLOAT,
              fuelPerLiter FLOAT,
              fuelPerGallon FLOAT,
              carInsurance FLOAT,
              carMaintenance FLOAT,
              vehicleRegistration FLOAT,
              tollFees FLOAT,
              carLoanInterestRates FLOAT,
              vehiclePurchasePrice FLOAT,
              drivingLicenseFees FLOAT,
              doctorsVisit FLOAT,
              specialistsVisit FLOAT,
              dentistsVisit FLOAT,
              eyeExam FLOAT,
              prescriptionMedication FLOAT,
              overTheCounterMedication FLOAT,
              healthInsurancePremiums FLOAT,
              healthInsuranceDeductibles FLOAT,
              emergencyRoomVisit FLOAT,
              hospitalStayPerNight FLOAT,
              physicalTherapy FLOAT,
              mentalHealthCounseling FLOAT,
              vaccinations FLOAT,
              preventiveHealthScreenings FLOAT,
              cosmeticProcedures FLOAT,
              opticalGlasses FLOAT,
              contactLenses FLOAT,
              shampooPrice FLOAT,
              toothpastePrice FLOAT,
              haircuts FLOAT,
              hairColoring FLOAT,
              manicurePedicureCost FLOAT,
              spaTreatment FLOAT,
              pairOfNikeRunningShoes FLOAT,
              mensDressShirt FLOAT,
              mensSuit FLOAT,
              mensJeans FLOAT,
              mensCasualShoes FLOAT,
              mensFormalShoes FLOAT,
              womensDress FLOAT,
              womensJeans FLOAT,
              womensCasualShoes FLOAT,
              womensFormalShoes FLOAT,
              winterCoatForAdults FLOAT,
              summerDress FLOAT,
              sweater FLOAT,
              underwearMen FLOAT,
              underwearWomen FLOAT,
              socksMen FLOAT,
              socksWomen FLOAT,
              sportsWear FLOAT,
              movieTicket FLOAT,
              theaterTicket FLOAT,
              concertTicket FLOAT,
              sportsEventTicket FLOAT,
              gymMembership FLOAT,
              swimmingPoolAccess FLOAT,
              museumEntry FLOAT,
              zooEntry FLOAT,
              amusementParkEntry FLOAT,
              bowling FLOAT,
              miniGolf FLOAT,
              videoGames FLOAT,
              streamingServices FLOAT,
              outdoorEquipmentRental FLOAT,
              themeParkAnnualPass FLOAT,
              childrensJeans FLOAT,
              childrensSneakers FLOAT,
              childrensWinterCoat FLOAT,
              daycareInfant FLOAT,
              daycareToddler FLOAT,
              childcareForSickDays FLOAT,
              earlyChildhoodEducationPrograms FLOAT,
              extracurricularActivities FLOAT,
              summerCamp FLOAT,
              preSchool FLOAT,
              primarySchoolFees FLOAT,
              secondarySchoolFees FLOAT,
              privateSchoolFees FLOAT,
              universityTuition FLOAT,
              universityTuitionPrivate FLOAT,
              afterSchoolActivities FLOAT,
              specialEducationServices FLOAT,
              tutoring FLOAT,
              textbooks FLOAT,
              schoolSupplies FLOAT,
              languageClasses FLOAT,
              parentingClasses FLOAT,
              fitnessClass FLOAT,
              musicLessons FLOAT,
              danceLessons FLOAT,
              artClasses FLOAT,
              readingMaterials FLOAT,
              educationalSoftware FLOAT,
              averageGrossSalary FLOAT,
              averageNetSalary FLOAT,
              minimumWage FLOAT,
              socialSecurityContributions FLOAT,
              pensionContributions FLOAT,
              costOfLivingIndex FLOAT,
              medianHouseholdIncome FLOAT,
              averageBonus FLOAT,
              legalConsultationPerHourRate FLOAT,
              accountingServicesPerHourRate FLOAT,
              ITSupportServicesPerHourRate FLOAT,
              technicianServicesPerHourRate FLOAT
            );
          `);

    // Create the table country_standard_info 
    await connection.query(`
            CREATE TABLE IF NOT EXISTS country_standard_info (
                id INT AUTO_INCREMENT PRIMARY KEY,
                country VARCHAR(255) NOT NULL,
                GDPNominal VARCHAR(50),
                GDPPerCapita FLOAT,
                GINI FLOAT,
                inflationOnConsumerPrices FLOAT,
                centralGovernmentDebt FLOAT,
                HDI DECIMAL(5, 3) NULL,
                humanCapitalIndex FLOAT,
                literacyRate FLOAT,
                lifeExpectancyRatio FLOAT,
                healthyLifeExpectancyRatio FLOAT,
                povertyRatio FLOAT,
                unemploymentPercentageOfTotalLabourForce FLOAT,
                grossNationalExpenditure FLOAT,
                currentHealthExpenditurePercentage FLOAT,
                researchAndDevelopmentExpenditure FLOAT,
                governmentExpenditureOnEducation FLOAT,
                internationalTourismExpenditureUSD FLOAT,
                numberOfInternationalTouristsArrival INT,
                militaryExpenditure FLOAT,
                densityOfDoctorsNumber FLOAT,
                densityOfNursesNumber FLOAT,
                densityOfPharmacistsNumber FLOAT,
                hospitalBedsPer1000Peoples FLOAT,
                pregnantWomenReceivingPrenatalCare FLOAT,
                agriculturalLand FLOAT,
                forestArea FLOAT,
                CO2Emission FLOAT,
                accessToElectricity FLOAT,
                accessToInternet FLOAT,
                annualFreshWaterWithdrawls FLOAT,
                timeRequiredToStartABusinessDays FLOAT,
                newBusinessesRegisteredNumber INT,
                newBusinessesRegistrationDensityPer1000People FLOAT,
                costOfBusinessStartUpProcedures FLOAT,
                importsOfGoodsAndServicesPercentageOfGDP FLOAT,
                fuelImportsPercentageOfMerchandiseImports FLOAT,
                costToImportBorderComplianceUSD FLOAT,
                costToImportDocumentryComplianceUSD FLOAT,
                timeToImportBorderComplianceHours FLOAT,
                timeToImportDocumentryComplianceHours FLOAT,
                exportsOfGoodsAndServicesPercentageOfGDP FLOAT,
                fuelExportsPercentageOfMerchandiseExports FLOAT,
                costToExportBorderComplianceUSD FLOAT,
                costToExportDocumentryComplianceUSD FLOAT,
                timeToExportBorderComplianceHours FLOAT,
                timeToExportDocumentryComplianceHours FLOAT,
                grossNationalSavings FLOAT,
                taxRevenue FLOAT,
                taxesOnExportsPercentageOfTaxRevenue FLOAT,
                taxesOnGoodsAndServicesPercentageOfRevenue FLOAT,
                taxesOnInternationalTradePercentageOfRevenue FLOAT,
                timeToPrepareAndPayTaxesHours FLOAT,
                customsAndOtherImportDutiesPercentageOfTaxRevenue FLOAT,
                corporateTaxRates VARCHAR(20),
                incomeTaxRates VARCHAR(20),
                salesTaxRates VARCHAR(20),
                propertyTaxRates VARCHAR(20),
                currencySymbol VARCHAR(20)
            );
          `);

    // Create the table us_state_general_info
    await connection.query(`
            CREATE TABLE IF NOT EXISTS us_state_general_info (
            id INT AUTO_INCREMENT PRIMARY KEY,
            state VARCHAR(255) NOT NULL,
            officialName VARCHAR(255),
            nicknames VARCHAR(255),
            landlockedStatus VARCHAR(20),
            capitalCity VARCHAR(255),
            latitude VARCHAR(50),
            longitude VARCHAR(50),
            mottoLatin VARCHAR(255),
            mottoEnglish VARCHAR(255),
            stateAnthemNative VARCHAR(255),
            stateAnthemEnglish VARCHAR(255),
            largestCity VARCHAR(255),
            demonyms VARCHAR(255),
            officialWebsites VARCHAR(50),
            ISO3166Code VARCHAR(20),
            areaInSqMile FLOAT,
            areaInSqKm FLOAT,
            waterPercentage VARCHAR(20),
            officialLanguages TEXT,
            stateAnimal VARCHAR(100),
            stateBird VARCHAR(100),
            stateFlower VARCHAR(100),
            stateColors VARCHAR(100),
            stateSport VARCHAR(100),
            stateTree VARCHAR(100),
            totalTimezones TEXT,
            timezoneNormal TEXT,
            timezoneSummer TEXT,
            DSTStart VARCHAR(50),
            DSTEnd VARCHAR(50),
            DSTDuration VARCHAR(20),
            population BIGINT,
            veteransPercentage FLOAT,
            veteransPercentageMale FLOAT,
            veteransPercentageFemale FLOAT,
            currencyName VARCHAR(50),
            currencySymbol VARCHAR(20),
            startOfWeek VARCHAR(20),
            drivingSide VARCHAR(20),
            callingCode VARCHAR(50)
            );
        `);

    // Create the table us_state_cost_info
    await connection.query(`
            CREATE TABLE IF NOT EXISTS us_state_cost_info (
            id INT AUTO_INCREMENT PRIMARY KEY,
            state VARCHAR(255) NOT NULL,
            rent1bedroomflatInCityCenter FLOAT,
            rent2bedroomflatInCityCenter FLOAT,
            rent3bedroomflatInCityCenter FLOAT,
            rent1bedroomflatOutsideCityCenter FLOAT,
            rent2bedroomflatOutsideCityCenter FLOAT,
            rent3bedroomflatOutsideCityCenter FLOAT,
            mortgageRatesPerMonth FLOAT,
            realEstateAgentsCommissionFees FLOAT,
            homeFurnishing FLOAT,
            electricityCostPerMonth FLOAT,
            heatingCostPerMonth FLOAT,
            coolingCostPerMonth FLOAT,
            waterCostPerMonth FLOAT,
            wifiCostPerMonth FLOAT,
            mobilePhonePlanCostPerMonth FLOAT,
            cableTVServicePerMonth FLOAT,
            landlinePhoneServicePerMonth FLOAT,
            milk1Liter FLOAT,
            water1Liter FLOAT,
            bread500g FLOAT,
            rice1Kg FLOAT,
            eggsDozen FLOAT,
            cheese1Kg FLOAT,
            chickenBreasts1Kg FLOAT,
            beef1Kg FLOAT,
            apples1Kg FLOAT,
            bananas1Kg FLOAT,
            oranges1Kg FLOAT,
            tomatoes1Kg FLOAT,
            potatoes1Kg FLOAT,
            lemons1Kg FLOAT,
            onions1Kg FLOAT,
            lentils1Kg FLOAT,
            wineMidRangeBottle FLOAT,
            glassOfWine FLOAT,
            domesticBeerHalfLiter FLOAT,
            importedBeerHalfLiter FLOAT,
            domesticAlcohol1Liter FLOAT,
            brandedAlcohol1Liter FLOAT,
            mealAtInexpensiveRestaurant FLOAT,
            threeCourseMealForTwo FLOAT,
            fastFoodComboMeal FLOAT,
            coffee FLOAT,
            softDrink FLOAT,
            pizza FLOAT,
            takeoutDeliveryMeal FLOAT,
            cigarettesPackOf20 FLOAT,
            publicTransportPass FLOAT,
            singlePublicTransportTicket FLOAT,
            trainTickets FLOAT,
            airfareDomestic FLOAT,
            taxiStartFare FLOAT,
            taxiRatePerKm FLOAT,
            carRentalPerDay FLOAT,
            parkingFeesCityCenterPerHour FLOAT,
            parkingFeesOutsideCityCenterPerHour FLOAT,
            fuelPerLiter FLOAT,
            fuelPerGallon FLOAT,
            carInsurance FLOAT,
            carMaintenance FLOAT,
            vehicleRegistration FLOAT,
            tollFees FLOAT,
            carLoanInterestRates FLOAT,
            vehiclePurchasePrice FLOAT,
            drivingLicenseFees FLOAT,
            doctorsVisit FLOAT,
            specialistsVisit FLOAT,
            dentistsVisit FLOAT,
            eyeExam FLOAT,
            prescriptionMedication FLOAT,
            overTheCounterMedication FLOAT,
            healthInsurancePremiums FLOAT,
            healthInsuranceDeductibles FLOAT,
            emergencyRoomVisit FLOAT,
            hospitalStayPerNight FLOAT,
            physicalTherapy FLOAT,
            mentalHealthCounseling FLOAT,
            vaccinations FLOAT,
            preventiveHealthScreenings FLOAT,
            cosmeticProcedures FLOAT,
            opticalGlasses FLOAT,
            contactLenses FLOAT,
            shampooPrice FLOAT,
            toothpastePrice FLOAT,
            haircuts FLOAT,
            hairColoring FLOAT,
            manicurePedicureCost FLOAT,
            spaTreatment FLOAT,
            pairOfNikeRunningShoes FLOAT,
            mensDressShirt FLOAT,
            mensSuit FLOAT,
            mensJeans FLOAT,
            mensCasualShoes FLOAT,
            mensFormalShoes FLOAT,
            womensDress FLOAT,
            womensJeans FLOAT,
            womensCasualShoes FLOAT,
            womensFormalShoes FLOAT,
            winterCoatForAdults FLOAT,
            summerDress FLOAT,
            sweater FLOAT,
            underwearMen FLOAT,
            underwearWomen FLOAT,
            socksMen FLOAT,
            socksWomen FLOAT,
            sportsWear FLOAT,
            movieTicket FLOAT,
            theaterTicket FLOAT,
            concertTicket FLOAT,
            sportsEventTicket FLOAT,
            gymMembership FLOAT,
            swimmingPoolAccess FLOAT,
            museumEntry FLOAT,
            zooEntry FLOAT,
            amusementParkEntry FLOAT,
            bowling FLOAT,
            miniGolf FLOAT,
            videoGames FLOAT,
            streamingServices FLOAT,
            outdoorEquipmentRental FLOAT,
            themeParkAnnualPass FLOAT,
            childrensJeans FLOAT,
            childrensSneakers FLOAT,
            childrensWinterCoat FLOAT,
            daycareInfant FLOAT,
            daycareToddler FLOAT,
            childcareForSickDays FLOAT,
            earlyChildhoodEducationPrograms FLOAT,
            extracurricularActivities FLOAT,
            summerCamp FLOAT,
            preSchool FLOAT,
            primarySchoolFees FLOAT,
            secondarySchoolFees FLOAT,
            privateSchoolFees FLOAT,
            universityTuition FLOAT,
            universityTuitionPrivate FLOAT,
            afterSchoolActivities FLOAT,
            specialEducationServices FLOAT,
            tutoring FLOAT,
            textbooks FLOAT,
            schoolSupplies FLOAT,
            languageClasses FLOAT,
            parentingClasses FLOAT,
            fitnessClass FLOAT,
            musicLessons FLOAT,
            danceLessons FLOAT,
            artClasses FLOAT,
            readingMaterials FLOAT,
            educationalSoftware FLOAT,
            averageGrossSalary FLOAT,
            averageNetSalary FLOAT,
            minimumWage FLOAT,
            socialSecurityContributions FLOAT,
            pensionContributions FLOAT,
            costOfLivingIndex FLOAT,
            medianHouseholdIncome FLOAT,
            averageBonus FLOAT,
            legalConsultationPerHourRate FLOAT,
            accountingServicesPerHourRate FLOAT,
            ITSupportServicesPerHourRate FLOAT,
            technicianServicesPerHourRate FLOAT
    );
        `);

    // Create the table us_state_standard_info
    await connection.query(`
            CREATE TABLE IF NOT EXISTS us_state_standard_info (
            id INT AUTO_INCREMENT PRIMARY KEY,
            state VARCHAR(255) NOT NULL,
            population INT,
            HDI DECIMAL(5, 3) NULL,
            literacyRate FLOAT,
            lifeExpectancyRatio FLOAT,
            povertyRatio FLOAT,
            employmentRate FLOAT,
            GDPNominal FLOAT,
            GDPPerCapita FLOAT,
            GINI FLOAT,
            totalRegisteredPhysicians INT,
            totalRegisteredNurses INT,
            availableHospitalBeds INT,
            disabilityPercentage FLOAT,
            populationWithoutHealthInsuranceCoverage FLOAT,
            salesTaxRates VARCHAR(50),
            propertyTaxRates VARCHAR(50),
            gasAndFuelTaxRatesPerGallon FLOAT,
            beerTaxPerGallon FLOAT,
            incomeTaxRates VARCHAR(50),
            corporateTaxRates VARCHAR(50),
            medianAge FLOAT,
            sexRatioMalesPer100Females FLOAT,
            age60to64 FLOAT,
            age65to74 FLOAT,
            age75to84 FLOAT,
            age85AndOver FLOAT,
            medianIncomeDollars FLOAT,
            agricultureForestryFishing FLOAT,
            construction FLOAT,
            manufacturing FLOAT,
            wholesaleTrade FLOAT,
            retailTrade FLOAT,
            transportationAndWarehousing FLOAT,
            ITAndInformation FLOAT,
            financeAndRealEstate FLOAT,
            educationAndHealthCare FLOAT,
            artsEntertainmentRecreation FLOAT,
            publicAdministration FLOAT,
            workFromHome FLOAT,
            meanTravelTimeToWorkMinutes FLOAT,
            privateWageandSalaryWorkers FLOAT,
            governmentWorkers FLOAT,
            selfEmployedInNotOwnIncorporatedBusiness FLOAT,
            accessToInternet FLOAT,
            accessToElectricity FLOAT,
            forestArea FLOAT,
            agriculturalLand FLOAT,
            highSchoolGraduate FLOAT,
            associateDegreePercentage FLOAT,
            bachelorsDegreePercentage FLOAT,
            graduateDegreePercentage FLOAT,
            onlyEnglishSpeakingPercentage FLOAT,
            whiteRace INT,
            blackOrAfricanAmericanRace INT,
            americanIndianAndAlaskaNativeRace INT,
            asianRace INT,
            hawaiianAndPacificIslanderRace INT,
            twoOrMoreRaces INT,
            hispanicOrLatino INT,
            marriedCoupleHouseholdPercentage FLOAT,
            maleHouseholderPercentage FLOAT,
            femaleHouseholderPercentage FLOAT,
            averageFamilySize FLOAT,
            homeOwnershipRate FLOAT,
            medianGrossRent FLOAT,
            totalHousingUnits INT,
            marriedNotSeparatedPopulationPercentageMale FLOAT,
            marriedNotSeparatedPopulationPercentageFemale FLOAT,
            neverMarriedPopulationPercentageMale FLOAT,
            neverMarriedPopulationPercentageFemale FLOAT,
            separatedPopulationPercentageMale FLOAT,
            separatedPopulationPercentageFemale FLOAT,
            divorcedPopulationPercentageMale FLOAT,
            divorcedPopulationPercentageFemale FLOAT,
            widowedPopulationPercentageMale FLOAT,
            widowedPopulationPercentageFemale FLOAT
           );
        `);

    console.log('Tables created successfully');
  } catch (error) {
    console.error('Failed to initialize the database:', error);
  } finally {
    await connection.end();
  }
}

initializeDatabase();
