[build]
  publish = ".next"
  command = "npm run build"

[dev]
  command = "npm run dev"

[build.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"