const Database = require('better-sqlite3');
const path = require('path');

const dbPath = path.join(process.cwd(), 'comparedoo.db');
const db = new Database(dbPath, { verbose: console.log });

try {
  // country general
  db.exec(`
    CREATE TABLE IF NOT EXISTS country_general_info (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        country TEXT NOT NULL,
        capitalCity TEXT,
        largestCity TEXT,
        populationGrowthAnnual REAL,
        officialName TEXT,
        continent TEXT,
        landlockedStatus TEXT,
        nationalAnthemEnglish TEXT,
        nationalAnthemNative TEXT,
        currencyName TEXT,
        currencySymbol TEXT,
        nationalBird TEXT,
        nationalColors TEXT,
        nationalFlower TEXT,
        nationalSport TEXT,
        nationalAnimal TEXT,
        demonyms TEXT,
        drivingSide TEXT,
        callingCode TEXT,
        ISO3166Code TEXT,
        internetTLD TEXT,
        latitude TEXT,
        longitude TEXT,
        areaInSqKm REAL,
        areaInSqMile REAL,
        waterPercentage TEXT,
        officialLanguages TEXT,
        majorReligion TEXT,
        majorReligionPercentage REAL,
        governmentStatus TEXT,
        totalTimezones TEXT,
        timezoneNormal TEXT,
        timezoneSummer TEXT,
        DST TEXT,
        DSTStart TEXT,
        DSTEnd TEXT,
        DSTDuration TEXT,
        population TEXT,
        age0_14 REAL,
        age15_64 REAL,
        age65Plus REAL,
        fertilityRate REAL,
        mortalityRateFemale REAL,
        mortalityRateMale REAL,
        infantMortalityRate REAL,
        topCauseOfDeath TEXT,
        topCauseOfDeathNumber REAL,
        lowestCauseOfDeath TEXT,
        lowestCauseOfDeathNumber REAL,
        roadTrafficDeaths REAL,
        suicideDeaths REAL,
        numberOfNewHIVInfections REAL,
        prevalenceOfHypertensionPercentage REAL,
        adultObesityPercentage REAL,
        tobaccoConsumptionPercentage REAL,
        alcoholConsumptionPercentage REAL,
        startOfWeek TEXT,
        unitValueInUSD REAL
    );
`);

  // country cost
  db.exec(`
  CREATE TABLE IF NOT EXISTS country_cost_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    country TEXT NOT NULL,
    rent1bedroomflatInCityCenter REAL,
    rent2bedroomflatInCityCenter REAL,
    rent3bedroomflatInCityCenter REAL,
    rent1bedroomflatOutsideCityCenter REAL,
    rent2bedroomflatOutsideCityCenter REAL,
    rent3bedroomflatOutsideCityCenter REAL,
    mortgageRatesPerMonth REAL,
    realEstateAgentsCommissionFees REAL,
    homeFurnishing REAL,
    electricityCostPerMonth REAL,
    heatingCostPerMonth REAL,
    coolingCostPerMonth REAL,
    waterCostPerMonth REAL,
    wifiCostPerMonth REAL,
    mobilePhonePlanCostPerMonth REAL,
    cableTVServicePerMonth REAL,
    landlinePhoneServicePerMonth REAL,
    milk1Liter REAL,
    water1Liter REAL,
    bread500g REAL,
    rice1Kg REAL,
    eggsDozen REAL,
    cheese1Kg REAL,
    chickenBreasts1Kg REAL,
    beef1Kg REAL,
    apples1Kg REAL,
    bananas1Kg REAL,
    oranges1Kg REAL,
    tomatoes1Kg REAL,
    potatoes1Kg REAL,
    lemons1Kg REAL,
    onions1Kg REAL,
    lentils1Kg REAL,
    wineMidRangeBottle REAL,
    glassOfWine REAL,
    domesticBeerHalfLiter REAL,
    importedBeerHalfLiter REAL,
    domesticAlcohol1Liter REAL,
    brandedAlcohol1Liter REAL,
    mealAtInexpensiveRestaurant REAL,
    threeCourseMealForTwo REAL,
    fastFoodComboMeal REAL,
    coffee REAL,
    softDrink REAL,
    pizza REAL,
    takeoutDeliveryMeal REAL,
    cigarettesPackOf20 REAL,
    publicTransportPass REAL,
    singlePublicTransportTicket REAL,
    trainTickets REAL,
    airfareDomestic REAL,
    taxiStartFare REAL,
    taxiRatePerKm REAL,
    carRentalPerDay REAL,
    parkingFeesCityCenterPerHour REAL,
    parkingFeesOutsideCityCenterPerHour REAL,
    fuelPerLiter REAL,
    fuelPerGallon REAL,
    carInsurance REAL,
    carMaintenance REAL,
    vehicleRegistration REAL,
    tollFees REAL,
    carLoanInterestRates REAL,
    vehiclePurchasePrice REAL,
    drivingLicenseFees REAL,
    doctorsVisit REAL,
    specialistsVisit REAL,
    dentistsVisit REAL,
    eyeExam REAL,
    prescriptionMedication REAL,
    overTheCounterMedication REAL,
    healthInsurancePremiums REAL,
    healthInsuranceDeductibles REAL,
    emergencyRoomVisit REAL,
    hospitalStayPerNight REAL,
    physicalTherapy REAL,
    mentalHealthCounseling REAL,
    vaccinations REAL,
    preventiveHealthScreenings REAL,
    cosmeticProcedures REAL,
    opticalGlasses REAL,
    contactLenses REAL,
    shampooPrice REAL,
    toothpastePrice REAL,
    haircuts REAL,
    hairColoring REAL,
    manicurePedicureCost REAL,
    spaTreatment REAL,
    pairOfNikeRunningShoes REAL,
    mensDressShirt REAL,
    mensSuit REAL,
    mensJeans REAL,
    mensCasualShoes REAL,
    mensFormalShoes REAL,
    womensDress REAL,
    womensJeans REAL,
    womensCasualShoes REAL,
    womensFormalShoes REAL,
    winterCoatForAdults REAL,
    summerDress REAL,
    sweater REAL,
    underwearMen REAL,
    underwearWomen REAL,
    socksMen REAL,
    socksWomen REAL,
    sportsWear REAL,
    movieTicket REAL,
    theaterTicket REAL,
    concertTicket REAL,
    sportsEventTicket REAL,
    gymMembership REAL,
    swimmingPoolAccess REAL,
    museumEntry REAL,
    zooEntry REAL,
    amusementParkEntry REAL,
    bowling REAL,
    miniGolf REAL,
    videoGames REAL,
    streamingServices REAL,
    outdoorEquipmentRental REAL,
    themeParkAnnualPass REAL,
    childrensJeans REAL,
    childrensSneakers REAL,
    childrensWinterCoat REAL,
    daycareInfant REAL,
    daycareToddler REAL,
    childcareForSickDays REAL,
    earlyChildhoodEducationPrograms REAL,
    extracurricularActivities REAL,
    summerCamp REAL,
    preSchool REAL,
    primarySchoolFees REAL,
    secondarySchoolFees REAL,
    privateSchoolFees REAL,
    universityTuition REAL,
    universityTuitionPrivate REAL,
    afterSchoolActivities REAL,
    specialEducationServices REAL,
    tutoring REAL,
    textbooks REAL,
    schoolSupplies REAL,
    languageClasses REAL,
    parentingClasses REAL,
    fitnessClass REAL,
    musicLessons REAL,
    danceLessons REAL,
    artClasses REAL,
    readingMaterials REAL,
    educationalSoftware REAL,
    averageGrossSalary REAL,
    averageNetSalary REAL,
    minimumWage REAL,
    socialSecurityContributions REAL,
    pensionContributions REAL,
    costOfLivingIndex REAL,
    medianHouseholdIncome REAL,
    averageBonus REAL,
    legalConsultationPerHourRate REAL,
    accountingServicesPerHourRate REAL,
    ITSupportServicesPerHourRate REAL,
    technicianServicesPerHourRate REAL
  );
`);

  // country standard
  db.exec(`
    CREATE TABLE IF NOT EXISTS country_standard_info (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        country TEXT NOT NULL,
        GDPNominal TEXT,
        GDPPerCapita REAL,
        GINI REAL,
        inflationOnConsumerPrices REAL,
        centralGovernmentDebt REAL,
        HDI REAL,
        humanCapitalIndex REAL,
        literacyRate REAL,
        lifeExpectancyRatio REAL,
        healthyLifeExpectancyRatio REAL,
        povertyRatio REAL,
        unemploymentPercentageOfTotalLabourForce REAL,
        grossNationalExpenditure REAL,
        currentHealthExpenditurePercentage REAL,
        researchAndDevelopmentExpenditure REAL,
        governmentExpenditureOnEducation REAL,
        internationalTourismExpenditureUSD REAL,
        numberOfInternationalTouristsArrival Integer,
        militaryExpenditure REAL,
        densityOfDoctorsNumber REAL,
        densityOfNursesNumber REAL,
        densityOfPharmacistsNumber REAL,
        hospitalBedsPer1000Peoples REAL,
        pregnantWomenReceivingPrenatalCare REAL,
        agriculturalLand REAL,
        forestArea REAL,
        CO2Emission REAL,
        accessToElectricity REAL,
        accessToInternet REAL,
        annualFreshWaterWithdrawls REAL,
        timeRequiredToStartABusinessDays REAL,
        newBusinessesRegisteredNumber INTEGER,
        newBusinessesRegistrationDensityPer1000People REAL,
        costOfBusinessStartUpProcedures REAL,
        importsOfGoodsAndServicesPercentageOfGDP REAL,
        fuelImportsPercentageOfMerchandiseImports REAL,
        costToImportBorderComplianceUSD REAL,
        costToImportDocumentryComplianceUSD REAL,
        timeToImportBorderComplianceHours REAL,
        timeToImportDocumentryComplianceHours REAL,
        exportsOfGoodsAndServicesPercentageOfGDP REAL,
        fuelExportsPercentageOfMerchandiseExports REAL,
        costToExportBorderComplianceUSD REAL,
        costToExportDocumentryComplianceUSD REAL,
        timeToExportBorderComplianceHours REAL,
        timeToExportDocumentryComplianceHours REAL,
        grossNationalSavings REAL,
        taxRevenue REAL,
        taxesOnExportsPercentageOfTaxRevenue REAL,
        taxesOnGoodsAndServicesPercentageOfRevenue REAL,
        taxesOnInternationalTradePercentageOfRevenue REAL,
        timeToPrepareAndPayTaxesHours REAL,
        customsAndOtherImportDutiesPercentageOfTaxRevenue REAL,
        corporateTaxRates TEXT,
        incomeTaxRates TEXT,
        salesTaxRates TEXT,
        propertyTaxRates TEXT,
        currencySymbol TEXT
    );
`);


  // us-state general
  db.exec(`
    CREATE TABLE IF NOT EXISTS us_state_general_info (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      state TEXT NOT NULL,
      officialName TEXT,
      nicknames TEXT,
      landlockedStatus TEXT,
      capitalCity TEXT,
      latitude TEXT,
      longitude TEXT,
      mottoLatin TEXT,
      mottoEnglish TEXT,
      stateAnthemNative TEXT,
      stateAnthemEnglish TEXT,
      largestCity TEXT,
      demonyms TEXT,
      officialWebsites TEXT,
      ISO3166Code TEXT,
      areaInSqMile REAL,
      areaInSqKm REAL,
      waterPercentage TEXT,
      officialLanguages TEXT,
      stateAnimal TEXT,
      stateBird TEXT,
      stateFlower TEXT,
      stateColors TEXT,
      stateSport TEXT,
      stateTree TEXT,
      totalTimezones TEXT,
      timezoneNormal TEXT,
      timezoneSummer TEXT,
      DSTStart TEXT,
      DSTEnd TEXT,
      DSTDuration TEXT,
      population INTEGER,
      veteransPercentage REAL,
      veteransPercentageMale REAL,
      veteransPercentageFemale REAL,
      currencyName TEXT,
      currencySymbol TEXT,
      startOfWeek TEXT,
      drivingSide TEXT,
      callingCode TEXT
    );
  `);

  // us-state cost
  db.exec(`
    CREATE TABLE IF NOT EXISTS us_state_cost_info (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      state TEXT NOT NULL,
      rent1bedroomflatInCityCenter REAL,
      rent2bedroomflatInCityCenter REAL,
      rent3bedroomflatInCityCenter REAL,
      rent1bedroomflatOutsideCityCenter REAL,
      rent2bedroomflatOutsideCityCenter REAL,
      rent3bedroomflatOutsideCityCenter REAL,
      mortgageRatesPerMonth REAL,
      realEstateAgentsCommissionFees REAL,
      homeFurnishing REAL,
      electricityCostPerMonth REAL,
      heatingCostPerMonth REAL,
      coolingCostPerMonth REAL,
      waterCostPerMonth REAL,
      wifiCostPerMonth REAL,
      mobilePhonePlanCostPerMonth REAL,
      cableTVServicePerMonth REAL,
      landlinePhoneServicePerMonth REAL,
      milk1Liter REAL,
      water1Liter REAL,
      bread500g REAL,
      rice1Kg REAL,
      eggsDozen REAL,
      cheese1Kg REAL,
      chickenBreasts1Kg REAL,
      beef1Kg REAL,
      apples1Kg REAL,
      bananas1Kg REAL,
      oranges1Kg REAL,
      tomatoes1Kg REAL,
      potatoes1Kg REAL,
      lemons1Kg REAL,
      onions1Kg REAL,
      lentils1Kg REAL,
      wineMidRangeBottle REAL,
      glassOfWine REAL,
      domesticBeerHalfLiter REAL,
      importedBeerHalfLiter REAL,
      domesticAlcohol1Liter REAL,
      brandedAlcohol1Liter REAL,
      mealAtInexpensiveRestaurant REAL,
      threeCourseMealForTwo REAL,
      fastFoodComboMeal REAL,
      coffee REAL,
      softDrink REAL,
      pizza REAL,
      takeoutDeliveryMeal REAL,
      cigarettesPackOf20 REAL,
      publicTransportPass REAL,
      singlePublicTransportTicket REAL,
      trainTickets REAL,
      airfareDomestic REAL,
      taxiStartFare REAL,
      taxiRatePerKm REAL,
      carRentalPerDay REAL,
      parkingFeesCityCenterPerHour REAL,
      parkingFeesOutsideCityCenterPerHour REAL,
      fuelPerLiter REAL,
      fuelPerGallon REAL,
      carInsurance REAL,
      carMaintenance REAL,
      vehicleRegistration REAL,
      tollFees REAL,
      carLoanInterestRates REAL,
      vehiclePurchasePrice REAL,
      drivingLicenseFees REAL,
      doctorsVisit REAL,
      specialistsVisit REAL,
      dentistsVisit REAL,
      eyeExam REAL,
      prescriptionMedication REAL,
      overTheCounterMedication REAL,
      healthInsurancePremiums REAL,
      healthInsuranceDeductibles REAL,
      emergencyRoomVisit REAL,
      hospitalStayPerNight REAL,
      physicalTherapy REAL,
      mentalHealthCounseling REAL,
      vaccinations REAL,
      preventiveHealthScreenings REAL,
      cosmeticProcedures REAL,
      opticalGlasses REAL,
      contactLenses REAL,
      shampooPrice REAL,
      toothpastePrice REAL,
      haircuts REAL,
      hairColoring REAL,
      manicurePedicureCost REAL,
      spaTreatment REAL,
      pairOfNikeRunningShoes REAL,
      mensDressShirt REAL,
      mensSuit REAL,
      mensJeans REAL,
      mensCasualShoes REAL,
      mensFormalShoes REAL,
      womensDress REAL,
      womensJeans REAL,
      womensCasualShoes REAL,
      womensFormalShoes REAL,
      winterCoatForAdults REAL,
      summerDress REAL,
      sweater REAL,
      underwearMen REAL,
      underwearWomen REAL,
      socksMen REAL,
      socksWomen REAL,
      sportsWear REAL,
      movieTicket REAL,
      theaterTicket REAL,
      concertTicket REAL,
      sportsEventTicket REAL,
      gymMembership REAL,
      swimmingPoolAccess REAL,
      museumEntry REAL,
      zooEntry REAL,
      amusementParkEntry REAL,
      bowling REAL,
      miniGolf REAL,
      videoGames REAL,
      streamingServices REAL,
      outdoorEquipmentRental REAL,
      themeParkAnnualPass REAL,
      childrensJeans REAL,
      childrensSneakers REAL,
      childrensWinterCoat REAL,
      daycareInfant REAL,
      daycareToddler REAL,
      childcareForSickDays REAL,
      earlyChildhoodEducationPrograms REAL,
      extracurricularActivities REAL,
      summerCamp REAL,
      preSchool REAL,
      primarySchoolFees REAL,
      secondarySchoolFees REAL,
      privateSchoolFees REAL,
      universityTuition REAL,
      universityTuitionPrivate REAL,
      afterSchoolActivities REAL,
      specialEducationServices REAL,
      tutoring REAL,
      textbooks REAL,
      schoolSupplies REAL,
      languageClasses REAL,
      parentingClasses REAL,
      fitnessClass REAL,
      musicLessons REAL,
      danceLessons REAL,
      artClasses REAL,
      readingMaterials REAL,
      educationalSoftware REAL,
      averageGrossSalary REAL,
      averageNetSalary REAL,
      minimumWage REAL,
      socialSecurityContributions REAL,
      pensionContributions REAL,
      costOfLivingIndex REAL,
      medianHouseholdIncome REAL,
      averageBonus REAL,
      legalConsultationPerHourRate REAL,
      accountingServicesPerHourRate REAL,
      ITSupportServicesPerHourRate REAL,
      technicianServicesPerHourRate REAL
    );
  `);

  // us-state standard
  db.exec(`
  CREATE TABLE IF NOT EXISTS us_state_standard_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    state TEXT NOT NULL,
    population INTEGER,
    HDI REAL,
    literacyRate REAL,
    lifeExpectancyRatio REAL,
    povertyRatio REAL,
    employmentRate REAL,
    GDPNominal REAL,
    GDPPerCapita REAL,
    GINI REAL,
    totalRegisteredPhysicians INTEGER,
    totalRegisteredNurses INTEGER,
    availableHospitalBeds INTEGER,
    disabilityPercentage REAL,
    populationWithoutHealthInsuranceCoverage REAL,
    salesTaxRates TEXT,
    propertyTaxRates TEXT,
    gasAndFuelTaxRatesPerGallon REAL,
    beerTaxPerGallon REAL,
    incomeTaxRates TEXT,
    corporateTaxRates TEXT,
    medianAge REAL,
    sexRatioMalesPer100Females REAL,
    age60to64 REAL,
    age65to74 REAL,
    age75to84 REAL,
    age85AndOver REAL,
    medianIncomeDollars REAL,
    agricultureForestryFishing REAL,
    construction REAL,
    manufacturing REAL,
    wholesaleTrade REAL,
    retailTrade REAL,
    transportationAndWarehousing REAL,
    ITAndInformation REAL,
    financeAndRealEstate REAL,
    educationAndHealthCare REAL,
    artsEntertainmentRecreation REAL,
    publicAdministration REAL,
    workFromHome REAL,
    meanTravelTimeToWorkMinutes REAL,
    privateWageandSalaryWorkers REAL,
    governmentWorkers REAL,
    selfEmployedInNotOwnIncorporatedBusiness REAL,
    accessToInternet REAL,
    accessToElectricity REAL,
    forestArea REAL,
    agriculturalLand REAL,
    highSchoolGraduate REAL,
    associateDegreePercentage REAL,
    bachelorsDegreePercentage REAL,
    graduateDegreePercentage REAL,
    onlyEnglishSpeakingPercentage REAL,
    whiteRace INTEGER,
    blackOrAfricanAmericanRace INTEGER,
    americanIndianAndAlaskaNativeRace INTEGER,
    asianRace INTEGER,
    hawaiianAndPacificIslanderRace INTEGER,
    twoOrMoreRaces INTEGER,
    hispanicOrLatino INTEGER,
    marriedCoupleHouseholdPercentage REAL,
    maleHouseholderPercentage REAL,
    femaleHouseholderPercentage REAL,
    averageFamilySize REAL,
    homeOwnershipRate REAL,
    medianGrossRent REAL,
    totalHousingUnits INTEGER,
    marriedNotSeparatedPopulationPercentageMale REAL,
    marriedNotSeparatedPopulationPercentageFemale REAL,
    neverMarriedPopulationPercentageMale REAL,
    neverMarriedPopulationPercentageFemale REAL,
    separatedPopulationPercentageMale REAL,
    separatedPopulationPercentageFemale REAL,
    divorcedPopulationPercentageMale REAL,
    divorcedPopulationPercentageFemale REAL,
    widowedPopulationPercentageMale REAL,
    widowedPopulationPercentageFemale REAL
  );
  `);

  console.log('Database initialized and tables created successfully');

} catch (error) {
  console.error('Failed to initialize and populate the database:', error);
} finally {
  db.close();
}